apiVersion: v2
version: v0.0.10
appVersion: 0.0.1
type: application
description: watson-nlp
name: watson-nlp

dependencies:
  - name: test
    version: v0.0.10
    repository: https://raw.githubusercontent.com/nheidloff/test-charts/main/index.yaml
