componentName: watson-nlp
serviceType: ClusterIP

registries:
  - name: watson
    url: wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com
# - my-reg:
#   url: uk.icr.io/deleeuw-watson

imagePullSecrets:
  - artifactory-key

runtime:
  registry: watson
  image: watson-nlp-runtime:0.16.0_ubi8_py39

models:
  - registry: watson
    image: watson-nlp_syntax_izumo_lang_en_stock:0.0.4
# - registry: my-reg
#   image: mynamespace/mymodel:latest 